/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyect;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JFileChooser;
import javazoom.jl.player.Player;
/**
 *
 * @author Roney
 */
public class AssignAlarm extends javax.swing.JFrame implements Runnable{
    String sound;
    String title;
    String hours;
    String hh;
    String mm;
    String hourAlarm;
    String minuteAlarm;
       
    FileInputStream fis;
    BufferedInputStream bis;
    Player player;
    long all;

    /**
     * Creates new form AssignAlarm
     */
    public AssignAlarm() {
        initComponents();
        
        
        Thread t= new Thread(this);
        t.start();
        btnEscuchar.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        jcbHour = new javax.swing.JComboBox<>();
        lblHour = new javax.swing.JLabel();
        lblMinutes = new javax.swing.JLabel();
        jcbMinutes = new javax.swing.JComboBox<>();
        lblClock = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRingtone = new javax.swing.JButton();
        btnEscuchar = new javax.swing.JButton();
        btnSaveAlarm = new javax.swing.JButton();
        btnVerifyAlarms = new javax.swing.JButton();
        lblDateAlarm = new javax.swing.JLabel();
        jcbDay = new javax.swing.JComboBox<>();
        jcbMonth = new javax.swing.JComboBox<>();
        lblDay = new javax.swing.JLabel();
        lblMonth = new javax.swing.JLabel();
        lblAlarmName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblSound = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SET ALARM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 327, -1));

        lblTimer.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        lblTimer.setForeground(new java.awt.Color(255, 255, 255));
        lblTimer.setText("Timer:");
        jPanel1.add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jcbHour.setForeground(new java.awt.Color(51, 255, 0));
        jcbHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jPanel1.add(jcbHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        lblHour.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblHour.setForeground(new java.awt.Color(255, 255, 255));
        lblHour.setText("Hour:");
        jPanel1.add(lblHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        lblMinutes.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblMinutes.setForeground(new java.awt.Color(255, 255, 255));
        lblMinutes.setText("Minutes:");
        jPanel1.add(lblMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jcbMinutes.setForeground(new java.awt.Color(0, 255, 255));
        jcbMinutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        jPanel1.add(jcbMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        lblClock.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        lblClock.setForeground(new java.awt.Color(0, 0, 0));
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClock.setText("Clock");
        lblClock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 440, 60));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText(":");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 30, -1));

        btnRingtone.setBackground(new java.awt.Color(255, 255, 255));
        btnRingtone.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRingtone.setForeground(new java.awt.Color(0, 0, 0));
        btnRingtone.setText("Ringtone");
        btnRingtone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRingtoneActionPerformed(evt);
            }
        });
        jPanel1.add(btnRingtone, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        btnEscuchar.setBackground(new java.awt.Color(255, 153, 153));
        btnEscuchar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEscuchar.setForeground(new java.awt.Color(153, 255, 51));
        btnEscuchar.setText("Escuchar");
        btnEscuchar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscucharActionPerformed(evt);
            }
        });
        jPanel1.add(btnEscuchar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        btnSaveAlarm.setBackground(new java.awt.Color(255, 51, 51));
        btnSaveAlarm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSaveAlarm.setForeground(new java.awt.Color(51, 255, 51));
        btnSaveAlarm.setText("Guardar alarma");
        btnSaveAlarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAlarmActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveAlarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        btnVerifyAlarms.setBackground(new java.awt.Color(0, 0, 0));
        btnVerifyAlarms.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnVerifyAlarms.setForeground(new java.awt.Color(255, 255, 255));
        btnVerifyAlarms.setText("Modificar alarmas");
        btnVerifyAlarms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyAlarmsActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerifyAlarms, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        lblDateAlarm.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        lblDateAlarm.setForeground(new java.awt.Color(255, 255, 255));
        lblDateAlarm.setText("AlarmDate:");
        jPanel1.add(lblDateAlarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jcbDay.setForeground(new java.awt.Color(255, 255, 0));
        jcbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jcbDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        jcbMonth.setForeground(new java.awt.Color(51, 255, 204));
        jcbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(jcbMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        lblDay.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblDay.setForeground(new java.awt.Color(255, 255, 255));
        lblDay.setText("Day:");
        jPanel1.add(lblDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        lblMonth.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblMonth.setForeground(new java.awt.Color(255, 255, 255));
        lblMonth.setText("Month:");
        jPanel1.add(lblMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        lblAlarmName.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblAlarmName.setForeground(new java.awt.Color(255, 255, 255));
        lblAlarmName.setText("Alarm name:");
        jPanel1.add(lblAlarmName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, 30));

        lblSound.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        lblSound.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblSound, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 180, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveAlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAlarmActionPerformed
        String alarmName= txtName.getText();
        String hour= jcbHour.getSelectedItem().toString();
        String minutes= jcbMinutes.getSelectedItem().toString();
        String day= jcbDay.getSelectedItem().toString();
        String month= jcbMonth.getSelectedItem().toString();
        String state= "On";
        
        String alarm_hour= ""+hour.toString()+":"+minutes.toString()+":00";
        String alarm_date ="2024-"+month.toString()+"-"+day.toString()+"";
        
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/alarm_clock", "root", "runnyo312zse:+0ñ")) {
        // Crear la sentencia SQL de inserción
        String sql = "INSERT INTO Alarms (alarm_name, alarm_hour, alarm_date, state) VALUES (?, ?, ?, ?)";
        try (PreparedStatement statement = conn.prepareStatement(sql)) {
            // Establecer los parámetros en la sentencia SQL
            statement.setString(1, alarmName);
            statement.setString(2, alarm_hour);
            statement.setString(3, alarm_date);
            statement.setString(4, state);
            // Ejecutar la sentencia SQL
            int rowsInserted = statement.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Alarma guardada correctamente.");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar la alarma", "Error", HEIGHT);
    }
        if(lblSound.getText()!=""){
            System.out.println(alarm_hour);
            alarmActivated(Integer.valueOf(hour), Integer.valueOf(minutes), state.toString());
        }
        else{
            JOptionPane.showMessageDialog(null, "Para asignar una alarma, debe seleccionar un tema primero");
        }
    }//GEN-LAST:event_btnSaveAlarmActionPerformed

    public void chooseSong(){
        JFileChooser jfc= new JFileChooser();
        int soundInt=  jfc.showOpenDialog(null); 
        if(soundInt== JFileChooser.APPROVE_OPTION){
            File alarmMusic= jfc.getSelectedFile();
            sound = alarmMusic.getAbsolutePath();
            title = jfc.getSelectedFile().getName();
        }else if(soundInt == JFileChooser.CANCEL_OPTION){
            JOptionPane.showMessageDialog(null, "No has escogido un tema de alarma", "Error", HEIGHT);
        }
    }
    
    public void listenSong(){
        try {
            fis= new FileInputStream(sound);
            bis = new BufferedInputStream(fis);
            player = new Player(bis);
            all = fis.available();
            new Thread(){
                public void run(){
                    try{
                        player.play();
                    }catch(Exception e){
                        
                    }
                }
            }.start();
        } catch (Exception e) {
        }
    }
    
    public void alarmActivated(final int hour, final int minute, String value ){
        Thread t= new Thread(){
            public void run(){
            int time=0;
            while(time==0){
                Calendar c= Calendar.getInstance();
                int h= c.get(Calendar.HOUR);
                int m= c.get(Calendar.MINUTE);
                
                if(hour==h && minute==m && value=="On"){
                    listenSong();
                    JOptionPane.showConfirmDialog(null, "Stop Alarm","Yes or no?", JOptionPane.CLOSED_OPTION);
                    stopAlarm();
                    break;
                    
                }
            }
        }
        };t.start();
        
    }
    
    public void stopAlarm(){
        if(player!=null){
            player.close();
        }
    }
    private void btnVerifyAlarmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyAlarmsActionPerformed
        ModificateAlarm ma= new ModificateAlarm();
        ma.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVerifyAlarmsActionPerformed

    private void btnEscucharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscucharActionPerformed
        if(btnEscuchar.getText().equals("Escuchar")){
            listenSong();
            btnEscuchar.setText("Stop Sound");
            btnSaveAlarm.setEnabled(false);
            
        }else if(btnEscuchar.getText().equals("Stop Sound")){
            stopAlarm();
            btnEscuchar.setText("Escuchar");
            btnSaveAlarm.setEnabled(true);
        }
    }//GEN-LAST:event_btnEscucharActionPerformed

    private void btnRingtoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRingtoneActionPerformed
        chooseSong();
        if(!sound.equals(null)){
            lblSound.setText("Alarm Music: "+title);
        }
        btnEscuchar.setEnabled(true);
    }//GEN-LAST:event_btnRingtoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignAlarm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnEscuchar;
    private javax.swing.JButton btnRingtone;
    private javax.swing.JButton btnSaveAlarm;
    private javax.swing.JButton btnVerifyAlarms;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JComboBox<String> jcbDay;
    public static javax.swing.JComboBox<String> jcbHour;
    private javax.swing.JComboBox<String> jcbMinutes;
    private javax.swing.JComboBox<String> jcbMonth;
    private javax.swing.JLabel lblAlarmName;
    public static javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblDateAlarm;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblMinutes;
    private javax.swing.JLabel lblMonth;
    public static javax.swing.JLabel lblSound;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
    public void run(){
    while(true){
        Calendar c= Calendar.getInstance();
        SimpleDateFormat sdf= new SimpleDateFormat("hh:mm:ss");
        Date d= c.getTime();
        hours= sdf.format(d);
        lblClock.setText(hours);
    }
    }
}
