/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyect;


import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author Roney
 */
public class ModificateAlarm extends javax.swing.JFrame {

    DefaultTableModel dtm= new DefaultTableModel();
    public ModificateAlarm() {
        initComponents();
        String [] prendas= new String[]{
            "Alarm_ID", "Alarm_Name", "Alarm_Hour", "Alarm_Date", "State"
        };
        dtm.setColumnIdentifiers(prendas);
        tblAlarms.setModel(dtm);
        
        llenarComboBox("alarm_id", jcbID);
        llenarTabla();
        
    }

    public void llenarComboBox(String valor, JComboBox box){
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/alarm_clock", "root", "runnyo312zse:+0ñ")) {
        // Crear la sentencia SQL de inserción
        String sql = "SELECT * FROM Alarms";
        try (PreparedStatement statement = conn.prepareStatement(sql)) {
            
            ResultSet rs= statement.executeQuery();
            while(rs.next()){
                box.addItem(rs.getString(valor));
            }
            
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Datos no recibidos", "Error", HEIGHT);
    }
    }
    
    public void llenarTabla(){
        String [] datos= new String[5];
        
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/alarm_clock", "root", "runnyo312zse:+0ñ")) {
        // Crear la sentencia SQL de inserción
        String sql = "SELECT * FROM Alarms";
        try (PreparedStatement statement = conn.prepareStatement(sql)) {
            
            ResultSet rs= statement.executeQuery();
            while(rs.next()){
                datos[0]= Integer.toString(rs.getInt(1));
                datos[1]= rs.getString(2);
                datos[2]= rs.getString(3);
                datos[3]= rs.getString(4);
                datos[4]= rs.getString(5);
                dtm.addRow(datos);
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Datos no recibidos", "Error", HEIGHT);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbState = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlarms = new javax.swing.JTable();
        jcbID = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbHour = new javax.swing.JComboBox<>();
        jcbMinutes = new javax.swing.JComboBox<>();
        jcbDay = new javax.swing.JComboBox<>();
        jcbMonth = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modify Alarms");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 6, 179, -1));

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("State:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, -1, -1));

        jcbState.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jcbState.setForeground(new java.awt.Color(51, 255, 51));
        jcbState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On", "Off" }));
        jPanel1.add(jcbState, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 64, -1));

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alarm Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 153, 29));

        tblAlarms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAlarms);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 781, 259));

        jPanel1.add(jcbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, -1));

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alarm ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hour:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Minutes:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Day:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Month:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        jcbHour.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jcbHour.setForeground(new java.awt.Color(255, 255, 51));
        jcbHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jPanel1.add(jcbHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jcbMinutes.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jcbMinutes.setForeground(new java.awt.Color(255, 102, 0));
        jcbMinutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        jPanel1.add(jcbMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jcbDay.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jcbDay.setForeground(new java.awt.Color(102, 0, 255));
        jcbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jcbDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        jcbMonth.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jcbMonth.setForeground(new java.awt.Color(0, 255, 255));
        jcbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(jcbMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 220, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int id= Integer.parseInt(jcbID.getSelectedItem().toString());
        String alarmName= txtName.getText();
        String hour= jcbHour.getSelectedItem().toString();
        String minutes= jcbMinutes.getSelectedItem().toString();
        String day= jcbDay.getSelectedItem().toString();
        String month= jcbMonth.getSelectedItem().toString();
        String state= jcbState.getSelectedItem().toString();
        
        String alarm_hour= ""+hour.toString()+":"+minutes.toString()+":00";
        String alarm_date ="2024-"+month.toString()+"-"+day.toString()+"";
        
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/alarm_clock", "root", "runnyo312zse:+0ñ")) {
        // Crear la sentencia SQL de inserción
        String sql = "UPDATE Alarms SET alarm_name= ?, alarm_hour= ?, alarm_date= ?, state= ?  WHERE alarm_id= ?";
        try (PreparedStatement statement = conn.prepareStatement(sql)) {
            // Establecer los parámetros en la sentencia SQL
            statement.setString(1, alarmName);
            statement.setString(2, alarm_hour);
            statement.setString(3, alarm_date);
            statement.setString(4, state);
            statement.setInt(5, id);
            // Ejecutar la sentencia SQL
            int rowsInserted = statement.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Alarma actualizada correctamente");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar la alarma", "Error", HEIGHT);
    }
        int[] rows = tblAlarms.getSelectedRows();
        for (int i = 0; i < rows.length; i++) {
            dtm.removeRow(rows[i] - i);  
        }
        this.setVisible(false);
        
        llenarTabla();
        this.setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificateAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificateAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificateAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificateAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificateAlarm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbDay;
    private javax.swing.JComboBox<String> jcbHour;
    public static javax.swing.JComboBox<String> jcbID;
    private javax.swing.JComboBox<String> jcbMinutes;
    private javax.swing.JComboBox<String> jcbMonth;
    private javax.swing.JComboBox<String> jcbState;
    public static javax.swing.JTable tblAlarms;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
